Repository typedb/bazel-distribution, pull requests merged in 2019-07, with the labels that each got.

#148 Improve assemble_pip to autodetect files to include into Python tarball
  pip/assemble.py
  pip/rules.bzl
Labels: build, feature

#153 Schedule npm assembly action for local execution
  npm/assemble.py
  npm/rules.bzl
Labels: bug, build

#154 python_repackage rule implementation
  pip/BUILD
  pip/repackage.py
  pip/rules.bzl
Labels: build, feature

#159 Fix assemble_pip
  pip/assemble.py
Labels: bug

#161 Streamlined versioning for deploy_brew
  README.md
  brew/rules.bzl
Labels: build, refactor

#160 Streamlined versioning for assemble_apt
  README.md
  apt/rules.bzl
Labels: build, refactor

#162 Streamlined versioning for java_deps
  README.md
  common/java_deps.bzl
Labels: build, refactor

#163 Streamlined versioning for deploy_github
  github/rules.bzl
Labels: build, refactor

#164 Streamlined versioning for assemble_maven
  maven/_pom_replace_version.py
  maven/templates/rules.bzl
Labels: build, refactor

#165 Streamlined versioning for assemble_npm
  README.md
  maven/templates/rules.bzl
  npm/rules.bzl
Labels: build, refactor

#166 Streamlined versioning for assemble_pip
  README.md
  pip/rules.bzl
Labels: build, refactor

#167 Streamlined versioning for assemble_rpm
  README.md
  rpm/rules.bzl
Labels: build, refactor

#170 Prepare for upgrading of @build_bazel_rules_nodejs
  npm/assemble.py
  npm/rules.bzl
Labels: build
