Repository typedb/bazel-distribution, pull requests merged in 2019-09, with the labels that each got.

#177 Bugfix deploy_npm rule
  README.md
  npm/templates/BUILD
  npm/templates/deploy.py
  npm/templates/deploy.sh
Labels: bug, build

#179 Verify that referenced workspace exists in apt/rpm
  apt/generate_depends_file.py
  rpm/generate_spec_file.py
Labels: bug, build

#182 Make workspace_refs optional for assemble_maven
  maven/_pom_replace_version.py
  maven/templates/rules.bzl
Labels: build, feature

#183 Fix RPM package name
  rpm/rules.bzl
Labels: bug, build

#185 Makes part of `brew/templates/deploy.py` Python 3 compatible
  brew/templates/deploy.py
Labels: bug

#186 Fix deploy_maven rule to be compatible with Python 3
  maven/templates/deploy.py
Labels: bug, build

#187 Fix deploy_maven to be compatible with Python 3
  maven/templates/deploy.py
Labels: bug, build

#188 Makes part of `brew/templates/deploy.py` Python 3 compatible
  brew/templates/deploy.py
Labels: bug

#189 Bugfix deploy_brew to work with Python 3
  brew/templates/deploy.py
Labels: bug, build

#190 Bugfix hashlib invocations in deploy_brew and deploy_maven
  brew/templates/deploy.py
  maven/templates/deploy.py
Labels: bug, build
