Repository typedb/bazel-distribution, pull requests merged in 2019-03, with the labels that each got.

#63 Fix implementation of java_deps
  common/rules.bzl
Labels: bug, build

#65 Updated Maven rules: assemble_maven/deploy_maven
  WORKSPACE
  maven/BUILD
  maven/assemble.py
  maven/templates/BUILD
  maven/templates/deploy.py
  maven/templates/deploy.sh
  maven/templates/rules.bzl
Labels: build

#66 Bugfix assemble_maven: we don't use shell script anymore
  maven/templates/rules.bzl
Labels: bug, build

#68 Rename RPM output name so it's clear which target is built
  rpm/rules.bzl
Labels: build

#69 Use output_filename while choosing name for assemble_targz output
  common/rules.bzl
Labels: bug, build

#71 Fix broken deploy_rpm rule
  rpm/rules.bzl
Labels: bug, build

#72 Fix naming for Maven JARs inside distributions
  common/java_deps.py
  common/rules.bzl
Labels: bug, build

#73 Support for multiple targets in deploy_github
  github/deploy.py
  github/rules.bzl
Labels: build, feature

#74 Accept credentials from environment variable in deployment rules
  apt/templates/deploy.sh
  npm/templates/deploy.sh
  pip/templates/deploy.sh
  rpm/templates/deploy.sh
Labels: bug, build

#75 Make 'target' attribute non-mandatory for deploy_github
  github/rules.bzl
Labels: bug, build

#76 Bugfix deploy_github rule
  github/rules.bzl
Labels: bug, build

#82 deploy_maven() accepts 'version' in the command line argument
  maven/_pom_replace_version.py
  maven/templates/deploy.py
Labels: don't merge

#83 Allow deploy_github rule to deploy releases with no files
  github/deploy.py
Labels: bug, build

#85 Allow getting GitHub credential from enviroment variable
  github/deploy.py
Labels: build, feature

#87 Support Caskroom deployments for deploy_brew
  brew/rules.bzl
  brew/templates/deploy.py
Labels: build, feature

#88 Allow getting sha256 checksum from env variable instead of bazel target
  brew/rules.bzl
  brew/templates/deploy.py
Labels: build, feature

#90 Rename credential env vars
  apt/templates/deploy.sh
  brew/templates/deploy.py
  maven/templates/deploy.py
  npm/templates/deploy.sh
  pip/templates/deploy.sh
  rpm/templates/deploy.sh
Labels: build, refactor

#95 Make installation_dir an optional param to assemble_rpm
  rpm/rules.bzl
Labels: build, feature

#97 Assemble apt modifications
  apt/pkg_deb_modified_from_bazel/BUILD
  apt/pkg_deb_modified_from_bazel/archive.py
  apt/pkg_deb_modified_from_bazel/make_deb.py
  apt/pkg_deb_modified_from_bazel/path.bzl
  apt/pkg_deb_modified_from_bazel/pkg.bzl
  apt/rules.bzl
  rpm/rules.bzl
Labels: build, feature
