Repository typedb/bazel-distribution, pull requests merged in 2020-08, with the labels that each got.

#248 Update `assemble-maven` to take into account overriden transitive deps
  BUILD
  doc_hub.bzl
  maven/BUILD
  maven/deployment_rules_builder.py
  maven/rules.bzl
  maven/templates/BUILD
Labels: priority: high, type: refactor

#252 Fix old dependency on Skydoc, update rules_nodejs
  BUILD
  README.md
  WORKSPACE
  bazelbuild_rules_python-export-requirements-bzl-for-stardoc.patch
  common/dependencies.bzl
  doc_hub.bzl
  maven/BUILD
  npm/rules.bzl
  npm/templates/deploy.py
Labels: priority: high, type: build

#254 Make `assemble-npm` function correctly when run with RBE
  npm/rules.bzl
Labels: priority: high, type: build

#255 Update npm rules v2
  npm/rules.bzl
Labels: priority: high, type: build

#253 Extends artifact_extractor to support zip decompression
  artifact/rules.bzl
Labels: type: build

#257 Update npm rules - revert use of target package path
  npm/assemble.py
  npm/rules.bzl
Labels: priority: high, type: build
