Repository typedb/bazel-distribution, pull requests merged in 2021-01, with the labels that each got.

#279 deploy_github: fill in version
  github/templates/deploy.py
Labels: priority: high, type: build, type: feature

#280 Fix artifact_extractor rule
  artifact/rules.bzl
Labels: priority: high, type: bug, type: refactor

#281 Fix assemble-pip to skip --extra-index-url lines
  pip/assemble.py
Labels: priority: high, type: bug

#282 Adapt to new Grabl automation.yml syntax
  .grabl/automation.yml
Labels: type: bug, type: build

#283 Make python_repackage work with nested packages
  pip/repackage.py
  pip/rules.bzl
Labels: priority: high, type: bug
