Repository typedb/bazel-distribution, pull requests merged in 2021-12, with the labels that each got.

#326 Platform JVM assembler fixes
  platform/jvm/BUILD
  platform/jvm/JVMPlatformAssembler.kt
  platform/jvm/Shell.kt
  platform/jvm/rules.bzl
Labels: type: bug, priority: high

#328 Allow assemble_crate packages to be created in root Bazel package
  crates/CrateAssembler.kt
Labels: type: bug, type: build

#327 Add maven_artifacts without versions
  maven/deps.bzl
Labels: type: bug, priority: high

#325 Automatically collect crate dependencies
  README.md
  crates/rules.bzl
Labels: type: build, type: feature

#329 Fix class naming for Java builder targets
  maven/BUILD
Labels: type: bug
