Repository typedb/bazel-distribution, pull requests merged in 2021-03, with the labels that each got.

#288 Allow overriding artifacts in existing release
  github/templates/deploy.py
Labels: type: feature

#289 Fix deploy_brew rule to be compatible with Python 2
  brew/templates/deploy.py
Labels: type: bug

#290 Fix deploy_brew rule for non-zip targets
  brew/templates/deploy.py
Labels: priority: high, type: bug

#291 Fix producing .tar.gz archives with long filenames
  BUILD
  bazelbuild_rules_pkg-fix-tarfile-format.patch
  common/deps.bzl
Labels: priority: high, type: bug, type: build

#292 Improve assemble_maven to support merging JARs
  maven/BUILD
  maven/Repackager.kt
  maven/rules.bzl
Labels: type: build, type: feature

#293 Updated version of assemble_maven rewritten in Kotlin
  WORKSPACE
  common/deps.bzl
  maven/BUILD
  maven/JarAssembler.kt
  maven/PomGenerator.kt
  maven/deps.bzl
  maven/new_rules.bzl
Labels: priority: high, type: build, type: refactor

#294 Fix not being able to deploy Maven artifacts
  maven/new_rules.bzl
Labels: priority: blocker, type: bug, type: build

#295 Address review comments in assemble_maven
  WORKSPACE
  maven/new_rules.bzl
Labels: priority: high, type: build, type: refactor
