Repository typedb/bazel-distribution, pull requests merged in 2023-09, with the labels that each got.

#384 Update Maven rules to support platform profiles and Windows deployment
  maven/PomGenerator.kt
  maven/rules.bzl
  maven/templates/deploy.py
Labels: domain: maven

#383 Update pip rules to support native bdists and Windows deployment
  WORKSPACE
  pip/assemble.py
  pip/requirements.txt
  pip/rules.bzl
  pip/templates/deploy.py
Labels: type: feature, priority: blocker

#386 Update artifact extractor to be compatible with updated rules_pkg
  artifact/rules.bzl
Labels: priority: blocker, domain: build

#388 Assemble external workspace dependencies into Cargo dependencies
  crates/CrateAssembler.kt
  crates/CrateDeployer.kt
  crates/rules.bzl
  crates/templates/deploy.sh
  maven/PomGenerator.kt
Labels: type: bug, priority: blocker, domain: build

#387 Support architecture specific brew formulae
  brew/rules.bzl
  brew/templates/deploy.py
  common/checksum/rules.bzl
  platform/BUILD
  platform/constraints.bzl
  platform/jvm/rules.bzl
Labels: type: refactor, priority: blocker, domain: build
